clear all
set more off, perm

import delimited using rankings.csv, varn(1) clear
duplicates drop institution, force
order institution overall *
drop if institution == "Institution"
ds institution, not
foreach var of varlist `r(varlist)' {
	destring `var', replace ignore('---')
}
keep if regexm(institution, "University") | regexm(institution, "College") | regexm(institution, "School") | regexm(institution, "Institute of Technology") | regexm(institution, "Universit") | regexm(institution, "universit") | regexm(institution, "Facult") | regexm(institution, "Depart")
keep if !missing(student)

replace institution = subinstr(institution, "Department of Economics, ", "", .)
replace institution = subinstr(institution, "Department of Economics and Business, ", "", .)
replace institution = subinstr(institution, "College of Business and Behavioral Science, ", "", .)
replace institution = subinstr(institution, "Economics Department, ", "", .)
replace institution = subinstr(institution, "School of Arts and Sciences, ", "", .)
replace institution = subinstr(institution, "Finance and Graduate School of Business, ", "", .)
replace institution = subinstr(institution, "School of Economics and Management, ", "", .)
replace institution = subinstr(institution, "School of Business and Economics, ", "", .)
replace institution = subinstr(institution, "Faculty of Economics, ", "", .)
replace institution = subinstr(institution, "Graduate School of Economics, ", "", .)
replace institution = subinstr(institution, "School of Economics, ", "", .)
replace institution = subinstr(institution, "Eitan Berglas ", "", .)
replace institution = subinstr(institution, "Department of Economics and Related Studies, ", "", .)
replace institution = subinstr(institution, "Faculteit Economie en Bedrijfswetenschappen, ", "", .)
replace institution = subinstr(institution, "Faculteit der Economische Wetenschappen, ", "", .)
replace institution = subinstr(institution, "Dipartimento di Scienze Economiche, Alma Mater Studiorum - ", "", .)
replace institution = subinstr(institution, "Ã", "a", .)
replace institution = subinstr(institution, "Faculteit Economie en Bedrijfskunde, ", "", .)
replace institution = subinstr(institution, "akonomisk institutt, ", "", .)
replace institution = subinstr(institution, "akonomisk Institut, ", "", .)
replace institution = subinstr(institution, "School of Business, Management and Economics, ", "", .)
replace institution = subinstr(institution, "Departamento de Economa­a, ", "", .)
replace institution = subinstr(institution, "Finance and Management, ", "", .)
replace institution = subinstr(institution, "College of Business and Economics, ", "", .)
replace institution = subinstr(institution, "Faculty of Arts and Social Sciences, ", "", .)
replace institution = subinstr(institution, "School of Economics and Finance, ", "", .)
replace institution = subinstr(institution, "Division of Social Sciences, ", "", .)
replace institution = subinstr(institution, `"""', "", .)
replace institution = subinstr(institution, "Ekonomiha¶gskolan, ", "", .)
replace institution = subinstr(institution, "Dipartimenti e Istituti di Scienze Economiche, ", "", .)
replace institution = subinstr(institution, "Facultat d'Economia i Empresa, ", "", .)
replace institution = subinstr(institution, "Nationalekonomiska Institutionen, ", "", .)
replace institution = subinstr(institution, "Department Volkswirtschaftlehre, ", "", .)
replace institution = subinstr(institution, "¤", "", .)
replace institution = subinstr(institution, "School of Economics and Political Science, ", "", .)
replace institution = subinstr(institution, "Fachbereich Wirtschaftswissenschaften, ", "", .)
replace institution = subinstr(institution, "International Business School, ", "", .)
replace institution = subinstr(institution, "Dipartimento di Economia e Statistica Cognetti de Martiis, ", "", .)
replace institution = subinstr(institution, "Facultad de Ciencia Econa³micas y Administrativas, ", "", .)
replace institution = subinstr(institution, "³", "", .)
replace institution = subinstr(institution, "Nationalekonomiska institutionen, ", "", .)
replace institution = subinstr(institution, "Dipartimento di Economia, Management e Metodi Quantitativi (DEMM), ", "", .)
replace institution = subinstr(institution, "Wirtschaftswissenschaftliche Fakultat, ", "", .)
replace institution = subinstr(institution, "Institut fa¼r Volkswirtschaftslehre, ", "", .)
replace institution = subinstr(institution, "Dipartimento di Economia, ", "", .)
replace institution = subinstr(institution, "Division of Economics, ", "", .)
replace institution = subinstr(institution, "Fakultat fa¼r Wirtschafts- und Sozialwissenschaften, ", "", .)
replace institution = subinstr(institution, "Economics Division, ", "", .)
replace institution = subinstr(institution, "Dipartimento di Scienze Economiche Marco Fanno, ", "", .)
replace institution = subinstr(institution, "Facultad de Ciencias Econamicas y Empresariales, ", "", .)
replace institution = subinstr(institution, "Da©partement de Sciences aconomiques, ", "", .)
replace institution = subinstr(institution, "©", "", .)
replace institution = subinstr(institution, "Facultad de Economa­a, ", "", .)
replace institution = subinstr(institution, "¨", "", .)
replace institution = subinstr(institution, "Wirtschaftswissenschaftliches Zentrum, ", "", .)
replace institution = subinstr(institution, "Facolta  di Economia Giorgio Fua , ", "", .)
replace institution = subinstr(institution, "  ", " ", .)
replace institution = subinstr(institution, "¼", "", .)
replace institution = subinstr(institution, "Fakultat far Volkswirtschaft und Statistik, ", "", .)
replace institution = subinstr(institution, "Faculty of Business and Economics, ", "", .)
replace institution = subinstr(institution, "Graduate Center, ", "", .)
replace institution = subinstr(institution, "Dipartimento di Economia e Finanza (DEF), ", "", .)
replace institution = subinstr(institution, "Dapartement d'aconomie / Universita d'Ottawa / University of Ottawa", "University of Ottawa", .)
replace institution = subinstr(institution, "; University", "", .)
replace institution = subinstr(institution, "Dipartimento di Scienze per l'Economia e l'Impresa, ", "", .)
replace institution = subinstr(institution, "Facultad de Economa­a y Empresa, ", "", .)
replace institution = subinstr(institution, "Mathematics and Statistics, ", "", .)
replace institution = subinstr(institution, "Dipartimento di Economia Marco Biagi, ", "", .)
replace institution = subinstr(institution, "Scuola di Economia e Statistica, ", "", .)
replace institution = subinstr(institution, "", "", .)
replace institution = subinstr(institution, "Dapartement d'aconomique, ", "", .)
replace institution = subinstr(institution, "¶", "", .)
replace institution = subinstr(institution, "acole d'aconomie, ", "", .)
replace institution = subinstr(institution, "Departamento Acadamico de Economa­a, ", "", .)
replace institution = subinstr(institution, "Fachbereich Volkswirtschaftslehre, ", "", .)
replace institution = subinstr(institution, "", "", .)
replace institution = subinstr(institution, "Wirtschaftswissenschaftlichen Fakultat, ", "", .)
replace institution = subinstr(institution, "Department of Economics and Finance, ", "", .)
replace institution = subinstr(institution, "Institut for Virksomhedsledelse og akonomi, ", "", .)
replace institution = subinstr(institution, "Wirtschafts- und Sozialwissenschaftliche Fakultat, ", "", .)
replace institution = subinstr(institution, "Institutt for akonomi, ", "", .)
replace institution = subinstr(institution, "Facolta di Economia, ", "", .)
replace institution = subinstr(institution, "Gutenberg School of Management and Economics, ", "", .)
replace institution = subinstr(institution, "Wirtschaftswissenschaftlicher Fachbereich, ", "", .)
replace institution = subinstr(institution, "W.P. Carey School of Business, ", "", .)
replace institution = subinstr(institution, "Wirtschaftswissenschaftliche Fakutat, ", "", .)
replace institution = subinstr(institution, "Monash Business School, ", "", .)
replace institution = subinstr(institution, "Stern School of Business, ", "", .)
replace institution = subinstr(institution, "Sciences aconomiques, ", "", .)
replace institution = subinstr(institution, "Volkswirtschaftliche Fakultat, ", "", .)
replace institution = subinstr(institution, "Abteilung far Volkswirtschaftslehre, ", "", .)
replace institution = subinstr(institution, "Tepper School of Business Administration, ", "", .)
replace institution = subinstr(institution, "Booth School of Business, ", "", .)
replace institution = subinstr(institution, "Graduate School of Business, ", "", .)
replace institution = subinstr(institution, "Sloan School of Management, ", "", .)
replace institution = subinstr(institution, "Tippie College of Business, ", "", .)
replace institution = subinstr(institution, "Department of Agricultural and Resource Economics, ", "", .)
replace institution = subinstr(institution, "Fakultat far Wirtschaftswissenschaften, ", "", .)
replace institution = subinstr(institution, "Centre d'aconomie de la Sorbonne, ", "", .)
replace institution = subinstr(institution, "Krannert School of Management, ", "", .)
replace institution = subinstr(institution, "Wharton School of Business, ", "", .)
replace institution = subinstr(institution, "Kellogg Graduate School of Management, ", "", .)
replace institution = subinstr(institution, "Kennedy School of Government, ", "", .)
replace institution = subinstr(institution, "William E. Simon Graduate School of Business Administration, ", "", .)
replace institution = subinstr(institution, "Harvard Business School, ", "", .)
replace institution = subinstr(institution, "UNSW Business School, ", "", .)
replace institution = subinstr(institution, "Centre d'aconomie de l'Universita Paris-Nord (CEPN), ", "", .)
replace institution = subinstr(institution, "Department of Economics Studies, ", "", .)
replace institution = subinstr(institution, "Michael G. Foster School of Business, ", "", .)
replace institution = subinstr(institution, "Dipartimento di Scienze Economiche e Aziendali, ", "", .)
replace institution = subinstr(institution, "Center for Development Economics, ", "", .)
replace institution = subinstr(institution, "Dipartimento di Statistica, Informatica, Applicazioni G. Parenti, ", "", .)
replace institution = subinstr(institution, "Dipartimento di Scienze Economiche e Statistiche (DISES), ", "", .)
replace institution = subinstr(institution, "Department of Agricultural & Applied Economics, ", "", .)
replace institution = subinstr(institution, "School of Management, ", "", .) if ~regexm(institution, " School")
replace institution = subinstr(institution, "College of Business, ", "", .) if ~regexm(institution, " College")
replace institution = subinstr(institution, "Fakultat far Wirtschaftswissenschaft, ", "", .)
replace institution = subinstr(institution, "Fachbereich Rechts- und Wirtschaftswissenschaften, ", "", .)
replace institution = subinstr(institution, "Adam Smith Business School, ", "", .)
replace institution = subinstr(institution, "Department of Accounting, Finance and Economics, ", "", .)
replace institution = subinstr(institution, "Faculta des sciences aconomiques, ", "", .)
replace institution = subinstr(institution, "Business School, ", "", .) if ~regexm(institution, " Business")
replace institution = subinstr(institution, "Kelley School of Business, ", "", .)
replace institution = subinstr(institution, "Charles H. Dyson School of Applied Economics and Management, ", "", .)
replace institution = subinstr(institution, "HEC acole de Gestion, ", "", .)
replace institution = subinstr(institution, "Fakultat Wirtschaft und Management, ", "", .)
replace institution = subinstr(institution, "Management School, ", "", .) if ~regexm(institution, " Management")
replace institution = subinstr(institution, "Departement Fiscale en Economische vakken, ", "", .)
replace institution = subinstr(institution, "Handelshagskolan, ", "", .)
replace institution = subinstr(institution, "New School for Social Research, ", "", .)
replace institution = subinstr(institution, "Faculteid der Rechtsgeleerdheid, ", "", .)
replace institution = subinstr(institution, "Andrew Young School of Policy Studies, ", "", .)
replace institution = subinstr(institution, "Fachbereich Wirtschaftswissenschaft, ", "", .)
replace institution = subinstr(institution, "School of Economic Sciences, ", "", .)
replace institution = subinstr(institution, "Quantitative and Applied Spatial Economic Research Laboratory (QASER Lab), ", "", .)
replace institution = subinstr(institution, "Poole College of Management, ", "", .)
replace institution = subinstr(institution, "Environment Department, ", "", .)
replace institution = subinstr(institution, "Faculta des Hautes atudes Commerciales (HEC), ", "", .)
replace institution = subinstr(institution, "Ourso College of Business, ", "", .)
replace institution = subinstr(institution, "Eller College of Management, ", "", .)
replace institution = subinstr(institution, "Institute for International Economic Studies (IIES), ", "", .)
replace institution = subinstr(institution, "UFR Droit, aconomie et Gestion, ", "", .)
replace institution = subinstr(institution, "Ross School of Business, ", "", .)
replace institution = subinstr(institution, "Faculta des Sociales et de Gestion (FSESG), ", "", .)
replace institution = subinstr(institution, "Center for Energy and Environmental Studies (CEES), ", "", .)
replace institution = subinstr(institution, "Darla Moore School of Business, ", "", .)
replace institution = subinstr(institution, "Crawford School of Public Policy, ", "", .)
replace institution = subinstr(institution, "Department of Agricultural Economics, ", "", .)
replace institution = subinstr(institution, "Fakulteit Ekonomiese en Bestuurswetenskappe, ", "", .)
replace institution = subinstr(institution, "acole des Sciences de la Gestion (ESG), ", "", .)
replace institution = subinstr(institution, "School of Business, ", "", .) if ~regexm(institution, " School")
replace institution = subinstr(institution, "Department of Agricultural, Food and Resource Economics, ", "", .)
replace institution = subinstr(institution, "Faculteit Management en Bestuur, ", "", .)
replace institution = subinstr(institution, "Departments of Applied Economics, ", "", .)
replace institution = subinstr(institution, "Warwick Business School, ", "", .)
replace institution = subinstr(institution, "Economic and Social History, ", "", .)
replace institution = subinstr(institution, "Terry College of Business, ", "", .)
replace institution = subinstr(institution, "Abteilung Wirtschaftswissenschaft, ", "", .)
replace institution = subinstr(institution, "Anderson Graduate School of Management, ", "", .)
replace institution = subinstr(institution, "Fakultat Wirtschaftswissenschaften, ", "", .)
replace institution = subinstr(institution, "Faculteit Toegepaste Economische Wetenschappen, ", "", .)
replace institution = subinstr(institution, "Facolta di Economia Richard M. Goodwin, ", "", .)
replace institution = subinstr(institution, "Nijmegen School of Management, ", "", .)
replace institution = subinstr(institution, "Researchcentrum voor Onderwijs en Arbeidsmarkt (ROA), ", "", .)
replace institution = subinstr(institution, "Fisher College of Business, ", "", .)
replace institution = subinstr(institution, "Finance and Accounting, ", "", .)
replace institution = subinstr(institution, "Weatherhead School of Management, ", "", .)
replace institution = subinstr(institution, "Keele Management School, ", "", .)
replace institution = subinstr(institution, "Sauder School of Business, ", "", .)
replace institution = subinstr(institution, "Department of Applied Economics, College of Agricultural, Food, and Environmental Sciences, ", "", .)
replace institution = subinstr(institution, "Smeal College of Business Administration, ", "", .)
replace institution = subinstr(institution, "Senter for teknologi, innovasjon og kultur (TIK), ", "", .)
replace institution = subinstr(institution, "La Trobe Business School, ", "", .)
replace institution = subinstr(institution, "Economics of Climate Change (Climatecon), Institut far Landschaftsarchitektur und Umweltplanung, ", "", .)
replace institution = subinstr(institution, "Birmingham Business School, ", "", .)
replace institution = subinstr(institution, "Cowles Foundation for Research in Economics, ", "", .)
replace institution = subinstr(institution, "Institut de Finance de Strasbourg, ", "", .)
replace institution = subinstr(institution, "Johnson Graduate School of Management, ", "", .)
replace institution = subinstr(institution, "Dapartement de Sciences aconomiques et de Gestion, ", "", .)
replace institution = subinstr(institution, "Dipartimento di Economia e Management, ", "", .)
replace institution = subinstr(institution, "H. John Heinz III School of Public Policy and Management, ", "", .)
replace institution = subinstr(institution, "Department of Engineering-Economic Systems and Operations Research, ", "", .)
replace institution = subinstr(institution, "Thaorie aconomique, Modalisation, Application (THEMA), ", "", .)
replace institution = subinstr(institution, "Faculta de Sciences aconomiques et de Gestion, ", "", .)
replace institution = subinstr(institution, "²", "", .)
replace institution = subinstr(institution, "School of Industrial & Labor Relations, ", "", .)
replace institution = subinstr(institution, "Institute of Development Studies, ", "", .)
replace institution = subinstr(institution, "Departament d'Economia Aplicada, ", "", .)
replace institution = subinstr(institution, "Harris School of Public Policy, ", "", .)
replace institution = subinstr(institution, "Institut Suparieur d'aconomie et Management (ISEM), ", "", .)
replace institution = subinstr(institution, "Department of Natural Resources and Environmental Management, ", "", .)
replace institution = subinstr(institution, "Department of Policy Analysis and Management, College of Human Ecology, ", "", .)
replace institution = subinstr(institution, "Departament d'Economia, ", "", .)
replace institution = subinstr(institution, "Walter A. Haas School of Business, ", "", .)
replace institution = subinstr(institution, "Institutionen far ekonomi, ", "", .)
replace institution = subinstr(institution, "º", "", .)
replace institution = subinstr(institution, "Business, ", "", .)
replace institution = subinstr(institution, "Volkswirtschaftslehre, ", "", .)
replace institution = subinstr(institution, "Faculta de sciences aconomiques, ", "", .)
replace institution = subinstr(institution, "Eindhoven Centre for Innovation Studies (Ecis), ", "", .)
replace institution = subinstr(institution, "Department of International Development (Queen Elizabeth House), ", "", .)
replace institution = subinstr(institution, "Wirtschaftsinformatik und Wirtschaftsrecht, ", "", .)
replace institution = subinstr(institution, "Departamento de Estadistica, Econometria, Investigacian Operativa, Organisacion de Empresas y Economa­a Aplicada, ", "", .)
replace institution = subinstr(institution, "Institut far Internationale Wirtschaftspolitik, ", "", .)
replace institution = subinstr(institution, "Fach Betriebswirtschaftslehre, ", "", .)
replace institution = subinstr(institution, "KaÂ¸", "", .)
replace institution = subinstr(institution, "Centre for Research and Analysis of Migration (CReAM), ", "", .)
replace institution = subinstr(institution, "Institutionen far Nationalekonomi, UmeaÂ¥", "Umea", .)
replace institution = subinstr(institution, "Scuola di Economia e Management, ", "", .)
replace institution = "United Nations University" if regexm(institution, "United Nations University")
replace institution = "Norwegian University of Science and Technology" if institution == "Institutt for Samfunnsa¸konomi, Norges teknisk-naturvitenskaplige universitet (NTNU)"
replace institution = "University of Rome Tor Vergata" if institution == "Facolta  di Economia, Universita  degli Studi di Roma Tor Vergata"
replace institution = "University of Mannheim" if institution == "Abteilung fa¼r Volkswirtschaftslehre, Universita¤t Mannheim"
replace institution = "University of Bonn" if institution == "Wirtschaftswissenschaftlicher Fachbereich, Rheinische Friedrich-Wilhelms-Universitat Bonn"
replace institution = "Geothe University Frankfurt" if institution == "Fachbereich Wirtschaftswissenschaft, Goethe Universitat Frankfurt am Main"
replace institution = "Ludwig Maximilian University of Munich" if institution == "Volkswirtschaftliche Fakultat, Ludwig-Maximilians-Universitat Manchen"
replace institution = "Aix-Marseille University" if regexm(institution, "Aix-Marseille")
replace institution = "Universite Catholique de Louvain" if institution == "acole des Sciences aconomiques de Louvain, Universita Catholique de Louvain"
replace institution = "University of British Columbia" if institution == "Vancouver University of British Columbia"
replace institution = "Aarhus University" if institution == "Institut for Ãkonomi, Aarhus Universitet"

ds institution, not
foreach var of varlist `r(varlist)' {
	bys institution: egen temp = min(`var')
	replace `var' = temp
	drop temp
}
duplicates drop institution, force
ds institution, not
foreach var of varlist `r(varlist)' {
	sort `var'
	replace `var' = _n if `var' !=.
}
sort student overall
compress

export delimited using rankings.csv, replace

exit, clear
